### ISSUE TITLE
NameError: uninitialized constant Hobbit::Render

### ISSUE THREAD

**Issue by etagwerker** [patriciomacadden/hobbit-contrib#15]
Hey! 

The current documentation is not entirely accurate for `Hobbit::Render` - It causes this error: `NameError: uninitialized constant Hobbit::Render`

As is, it should probably be: 

```
require 'hobbit'
require 'hobbit/render'

class App < Hobbit::Base
  include Hobbit::Render

  get '/' do
    # will render views/index.erb using views/layouts/application.erb as layout
    render 'index'
  end
end
```

Another alternative would be to change https://github.com/patriciomacadden/hobbit-contrib/blob/master/lib/hobbit/contrib.rb and add this line: 

```
require 'hobbit/render'
```

I can submit a PR for this. I prefer the second alternative. What do you think? 

Please let me know.

Thanks!

**Comment by patriciomacadden** [comment]
Hey @etagwerker!

`lib/hobbit/contrib.rb` has a `require 'hobbit/render'` sentence, but wrapped in a `begin-rescue` block. This is because `Hobbit::Render` requires `tilt`, which is an optional dependency (it's not on the gemspec as one could probably not want to use `Hobbit::Render`). 

Does it work if you include `tilt` in your `Gemfile` or keeps failing?

I'm happy to receive a PR if it solves your problem. :smile:

**Comment by etagwerker** [comment]
@patriciomacadden yeah, that was it. I had forgotten to add `tilt` to my project. I'll submit a PR to improve the documentation.
